version: "3"

services: 

  db:
    image: postgres
    container_name: "docker_db"
    restart: always
    environment:
       POSTGRES_DB: ts_api
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: root
    ports: 
      - "5432:5432"   
  web:
    depends_on:
      - db
    build: . 
    ports: 
      - "8080:8080"
    volumes: 
      - .:/nodejs_sequelize_express
    container_name: nodejs_sequelize_express
    command: yarn dev